package comp1110.ass2;

import java.util.Random;

public class TestUtility {
    static final int BASE_ITERATIONS = 100;
    static final int ROWS = 26;
    static final int COLS = 26;
    static final int TILES = 21;
    static final int ORIENTATIONS = 4;
    static final char BAD = Character.MAX_VALUE - 'Z';

    static final String PLACEMENTS[] = {
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFALKTDOQHCNJNBINCDPPOAJKGBJPPDPPAASPRCQLCDSRRCMIIDPJKDLQIBOSLDIIHARJQDUPEBHNKBTOJDUJQCMIFDLTMDMIDDNJPBTOADQHSCHLGD",
            "MMUAONRCOPFDKNLDONACNLKCPLHBMJSBJODCIPQBNOGBKINBMIEDNQOBJMFCMROBQKBCPOSDJPJAMNQBNHIDSJLCMLBAOFMBJRCAPRTDKGCARHPDQSIBKTTDISECLPPAGSGCJTRBKUDARSKDHLADPIMAQUJB",
            "MMUALOMCLQFDIOMAHQECGSSDMPDDONQCGTDAMKLALJAAIROBINBDIRNBLQCDHOPCKPCBNLQANQFAHLKAJLBDPONCFRGBOKLDHJJAPMTDNKGBFVOCNQIALRRARKHCDVKBORHAOOPDGQIACRRDPPEAIPTDLIJD",
            "MMUAKNTDMPHDLLMAONCCOQNCNKEBOJSCLQGAPJSALJDDOHMDPFIBKNODMMFCJLPBQPJBSJQBPNBAIJNAHIAAJQPDONIDMILDRHCCTKOASPGCNIKBKSECRHKCQLJBHILATKBBSFRAKPDDRLQDKRAAKRRAQLFB",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAIMPALKGDLKMDPJBBNKRDLRCDKRTBPPFBJOKALRGCJKSAQJHDLSNAMTIALVRASIDAGMLDGOADOOOALYJCFMLCMZCCPSQDPIECJXPAMOICFPQDGMAC",
            "MMUAMKRALODDMJPDNOHAPKMBMGAAKNSBPPADJOSBRQCDKMRCMQGAINNCONCCQJQALGDBOIQBRLGDOILBRSFDOQKATQBDTSKANFHDOHTDQHEATONDRUJCIMOARQJAKETAVRICOOMCVOBAWPPAPSIBKCLASUED",
            "MMUANOQDNQFCKNNAKMEDONTDINGDRNSBQOBBIPSCKJGBLKRDQQIBJPODNRHBNLOCHNCCFNPCSNDALHPAUMICNKMBNTJALHLAFOCBLUNAPOACRQLDVLJAXKKCLPDDKUKCWMFAKGMDJFABJWQCRPBBIITBPREB",
            "MMUAMLKCOKGCNLRAONEBPOOAMIJBOKLBLNJCPQOBMGBAQRQAMMCCPSKBNQCCPNNDSNFCPOSBNEFBMRPASKIATRTCPFECQRLANCBAMCMBJLADOHNDUNGCPJTASSIALPPBRQDDLTSDRLHCLJQBTIHANRMCILAC",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAPPKBMQIBONNBRLFBJMSBPRGBLRQBJKCBRNLASKHANPKBSIJANSOBNUHBTNLDUMADOTQDWMIAMJPAMHDAMWRDONCBOHPDWPEDVKMANFBDIORDLTGA",
            "MMUANLPCKLBAKJSAKIFDMORBOPBCNMPAQPCBMQQBJIECQROAJKHBSRQAMTGDLNLCLOEDKFMAKTCDSRMBPNGAOLTDNFFCHKKCITIARLTCPKADSQOCUPDCSNRAIHACTKSCKHJCWPKBJOICIRLAXRDDUJNAMEHC",
            "MMUANLMBOLIDPNRCPOJARMSBMKEDLJLBMKGCKITCKFHBLIRDLIDANLSBOIEAOGNBMHFDIEPBSOGCOFOCHCAARKOBKMCDKONDKDDALQPCJJBBLCKDKCJCJRTDIGAAKSQAJDIBMFLCFECATPKBQHBAUQQDVPFD",
            "MMUANOTBMLADKKPDNJICLPMALSECKOOBNQCAPOOCMIBCMSMDMLCAKOTBKRJCIQSBLSFDQOQDIOHCGONCMJGDRPQAENBBOSKDFQICFMPALSADKHRASRGBPIRCNHJDNTLANEFBFSNDGKDAOSSCNWECFTKBQSHA",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAOKRCRLIBPQSCTLJBPSLDPIHBLKKCKODBROQDQJGAMIOASIABVLMCHOIAQLPCMHBDOSKBMSCBLRQCMFCDOVLCNPFAKSRBHSHAPQNBJTEBPVPALDAB",
            "MMUAMLKCMIIBOLSBLJEBOKPCOOCCLMQBLHEDNPNBPLDAKGRBNRGBOQOAKKCBLEKBRKJCMSOBLPJCLLRARIDDIMTARMIBROTATHHBQPMBMNBCLIQARIAASQSCKTFCOKLCIEGAITPBLRACOQLAMVFCOSMAHRBA",
            "MMUAMPPDLPGCIPOAJOJCIRMBKQIAMPKCLRBAKSLBJUBCMKSAOKJDMSTAKVGCFRRDHUFBFVODLJIDKWQAQLHCKWKAORECHQLCNMAAKYNBMMCDHYPDHRDDPSSBGYECIPNAEPDBENRAIXHDNUTBRTACMVQBSLCC",
            "MMUAMPSCNOCAKONDOMJBIOSDNQIBILKBKLABLLPDFLBDGOKAJJFAIKPCMRIBEJNDKLBBEJLDLIGAMLQBPPDCMGRAOFDCNETCKIECGNTCOIEBQIOBQHCDPLQANTJBPQMAMUABPLLALJGBPSMBLEHCPFOAELHB",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFALQOBJRIAMKRDLOEALJTCQMHDSMNAJQCCIMQDPLAAOLMBQNAAIKRDTOCCSNSAKIICJTKBISGCLIKBQKGDHLPBKGBDMFLAQQHCIMLDIFDDOPQBQNFA",
            "MMUALOMALNACLOLAKLBAMMRBNNAAOMTDLQEBRMLBNNDAJMQBKPGCSOPCHLJDKJRAQNHBLHMBRNBCIQPDRQIDHMTBHIIBRRQAJJJBFKKASQEBSMODTSFCHPNBIOFCHNNDTKCASOSCKGGCNQODVLHCTMSCHRCA",
            "MMUAKMNAJOCALLODINHAHOQBFOJCKMKAKQIDLITBDNJBGMTBLODAEMOBINHACLSBMHGBJPSDNHCAOORBJJIAMPPAIOADKGKALSBCQOMBILBDQQQAGLECBORALGABQNLDTNGCVMPCPNECSRMDEQDDTQNDNQFA",
            "MMUAONSBOLBANKQAPPCCLNNBKPDCOQTAQQFAJRMCQMIBIOSAMRGAJMPAQTEDLKQAKQIAOLPASMFCTLMAMOJAVMRCUNDBKTKDWLHAKQRBKPBCRLLCHSAAUQKCUQECXNTBHNGBRJODWQHCPTLBUQACVRNBTSCC",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAONLALOAAIMQAMQHBNKRDGNEDFMPCNIIDPPLBDMBCCLOCNGHCLKKCKQICRNKCDLCBIQRCKJGCILSCLGGCFNPBIJJCISNDNPACGKMAJTCBPKQDDLDB",
            "MMUAMONAOMHCKMOAKOFBLQQDLSJCMSRDISEANQODJPCBNTSBOJJBHUMAINGANQPCHWDBHWLCLKAAPMNAHTBCIMRDONABHKMBQQBBGLSBKJGAHIPAMVDDHGTAIJIALTLBFHIAFWQBKIECIYKCGUCBQLKDJVHB",
            "MMUAONSBMNHDKMQAJODDQNRCNPACQKPBLLICSMRCPIIBJMSCPGFAQIMDOKBCQOPBNHBBNMODJJGANMKDOQEBOFLBOEECLPMBMFGBOSKBSJCAOVLCMDJAPPTBPUADNWNAIKDBPDTASUFBNFQDLSHCTUNAKICC",
            "MMUALMSBKKDBKJQCKOCCLJTDLOHAOOPBQPFCQNNCMKAAMIMDNQBCKNLASPGBOKOAPRGDINOARMFAOISDSLCCPGRCHJIDKNKAIQEDMSKDTJHASOTCNGBBHMPAFIJATIQDMEDAQKRAEJICFMMDISACQHNDLDJD",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAKQKAKNJDLRRAPJHBOLOBQKGDKKSCRLDAJPLDPPCASMLASKEDSPTDLRABIJRBUPCAHIMCVNGAHGKCMJBBNKPDHOFAVQPAEIHAFGQCLUIDGKNCHNAC",
            "MMUALONDKOABOOSBJNBCNQMAORJAHNLBRRGBPOSAQTEDNNODRPFDSOKDOLGCSMKDJNDCQSOAROCBLQTCOJFCTLQDJQIBMIQAOQHBLLPDNHCDENMDELEDMMRDQLDBNTRDNFHDKQNDCLADPNLDTJIDRJTDLEJD",
            "MMUAKNNDJNDCNLRAHNBCHKTANMHCENLAJMAAOJMBFPGDOITCQKFBJJSCKIJDKJQACNCAONKBELABFKPCHPIDCKODPPHCJHOCFLGADLKDRJEADPPBPRIDTJRDILEAQJQCIQBBHISBHMFAHRMBQNDBRMNAMOCA",
            "MMUALNTBJOFDJMQDIOFCGPKANOJBLNKBLNBBKQPDLNABMKMBJOEDOMTBKRCAKJRAKRCAHNLCKIDDMSNCHREBQMOCKIGDLKSDQNDBMQNDQPHAOOLAOKIASNPCGSBBQSOCIQACQPSDTLICJGQAIPJBLIMBRSHD",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAJPRAOJGAMPQAPPFAMJRBLPADPITCHPBAOHMCILEAQKSAPGIDNNKCKRGDPDPBMSICSLPCKKCCQRLBOCDCRKOAIOJDLIKDIOADNLQBQMHARNNAKNCD",
            "MMUALMMBMPECOOQCMQAAPOTDNRIAQPRBJNDCHNKBHLCBIKTARPFDNRMCQMICKOLARLJDIIPAKQFBIROCMLGDHQPCOQHDOLSAQQECLPLDSMGAKHNALGACULNCVKDDTNRAUOJANJQBWMCCMFODIHBCOESCUQBB",
            "MMUANNOAMLADKNSAMLBAMJODLMJCKPTBLIECIMLDOICCKLRCOOGAROQCMQGBNGKDIPIBKGPAMEFBRQQCKEABIRMBGMDATQNBENIDIDKBGPECMITBLSHAKMLBJIBBKUNDLJJBGLPCSMCACNMDTOHAMOSBHSDB",
            "MMUANMSDNNFAPLOCPMJARKMCKMEAOLQBPMAAMLQCNNJAMMLCSMACROKDLJHDSKODINDDPKPATJDDOMMDSJEBQONBQRGDQTLCMLBAPKPAKPGCTMTAVIICOURCILIDNSKALHCCQJRCPIBCWHSASRHAOWTDQUFA",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFALKRDQMJAJJQAPJGANPPAIMIAQMLBMJADPIQDQHHDQOPAIKCBNNKDHNDBPHMASPABSMTDUNFCPGOCGOHBVMSAQQGAWNKAHQCDUNLCHJIDIONAHQBD",
            "MMUANLLCLLICOLKDLMCBKJMBOIEANKSAMPJDPMQAIJJBMJLCJLEBOPOAJOFCHHPBOGBAHLQCPKIDRGRCHPHDOSTDRJAAGMTBHQCAOGKAENGDOSODSFDAHHSBIMHBMRNCDODAGMNAMJACHQPDHTFCLSRBIJGA",
            "MMUANMSDPLCBKNODPKJDMKPBKJBBPHTAKHDBPNTAQLEAKJQCMPGCOOLCJMBBSNSBQNHDTMKCJLGCLGPASQCDMIQDGMJAOKRCJGEDNFRAKNFCMEMDKEIALRNCPPDAQJODIJHCFJLDDJADSJKDFHICGLNCJOFB",
            "MMUAONNBMOHALPLBPNCAJPKBOPIAKOTDRPBBJMQDJNFBJPSASQEDIQPBJSECRQPDKRHDGRTAOMJCHNRCSNACIKMAGQGCKKNDSNACHQSBOMDBMKLDUPDCVPRAILFDSSOCUMBBIRMDWQCASTOBXPJDPMKDQLID",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAOJPBMPDANRQBKNCDMITBMTADONKBKIGBRNRBOSGDNRKAQLHAQKPCMUAAKGMAOVJDJGSBLUHCPRRDMLEBOIQCNWBDLSOCMVIDKOLBKVCALRLALRIA",
            "MMUANNNAQNJBSOTBPPBAOMMCSRFDUPOBOQHBUSMCWQCCWROBPLGDRSQCQQEATTRBXPHAPJLDONDCUOPCTNGCVUNBQSIDLNLBSQFCOHQBMICDKLRASJBCVOKATHICSMSCVPDBUSTCOOAAMGKDRHEBRGPDMHAA",
            "MMUAONPCMPGCLRQCOOFBLMOCPOGANNKAMRCDJNSDKPBBHPLDOQEALKQDHQCBOTRCRODAJLTDRMIBIONDHPFDQTMCTOEDLIPDKPABUQNCQKBBHSSAURIAQQLDTRJBKJRBFQHBIRMDOJABHMKAVPJAPNTDESDD",
            "MMUALMQBKKFANOLBMNHCOQMCJLBBMJRCOMFCNQPDHKCAIMKBLPDAMKLAJQIAPOOCLHCDHRODOIJCQITBQOADJRSCKFEAQKNBLDJBPPNARLIAPGMATLGDKIPCJSHAIOKAJFABQESAFLEAIIRCRPBARCTBIEGD",
    };

    static final String INVALID_PLACEMENTS[] = {
            "MMUAOONB",
            "MMUANNNB",
            "MMUANONCMNED",
            "MMUANONCLLEAMNMD",
            "MMUANONCLLEAOMMD"
    };

    static String badlyFormedTilePlacement(Random r) {
        char a = (char) ('A' + r.nextInt(ROWS));
        char bada = (char) ('A' + ROWS + r.nextInt(r.nextInt(BAD)));
        char b = (char) ('A' + r.nextInt(COLS));
        char badb = (char) ('A' + COLS + r.nextInt(BAD));
        char c = (char) ('A' + r.nextInt(TILES));
        char badc = (char) ('A' + TILES + r.nextInt(BAD));
        char d = (char) ('A' +  ORIENTATIONS);
        char badd = (char) ('A' + ORIENTATIONS + r.nextInt(BAD));
        String test = "";
        switch (r.nextInt(5)) {
            case 0:
                test += "" + bada + b + c + d;
                break;
            case 1:
                test += "" + a + badb + c + d;
                break;
            case 2:
                test += "" + a + b + badc + d;
                break;
            case 3:
                test += "" + a + b + c + badd;
                break;
            default:
                test += "" + bada + b + badc + badd;
        }
        return test;

    }
}
