package comp1110.ass2;

import java.util.Random;

public class TestUtility {
    static final int BASE_ITERATIONS = 100;
    static final int ROWS = 26;
    static final int COLS = 26;
    static final int TILES = 21;
    static final int ORIENTATIONS = 4;
    static final char BAD = Character.MAX_VALUE - 'Z';

    static char[] shuffleDeck(boolean red) {
        Random r = new Random();
        char[] rtn = new char[20];
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 10; j++) {
                int idx;
                do {
                    idx = r.nextInt(20);
                } while (rtn[idx] != 0);
                rtn[idx] = (char) ((red ? 'A' : 'K') + j);
            }
        }
        return rtn;
    }

    static final String PLACEMENTS[] = {
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAKJLAPPABQKMCJNECRLRBLQGBNPKBLPHDPRPBJOFAMRRDOKHCMINCOTGAQITDTIIBRPKCKIDCRSOBTPCCSRQASGCAQKPBQUADPRLCQNJAIPSBGOIB",
            "MMUAMLODKNJDLPTDKOBBJNOCJMBAOLPALJEDJPNBQLFAHNNCLKHBLRLCNKHDHKKBKSGANKQAMJDBOJQDQOACKVPCPNACOPMDJOIAPLLBHJDCJLMDGIFCFOTDJXCCRPSCHVGAGQRDJVCBSNKBEIECLLRCIZID",
            "MMUANMTDOOADNPRAPLBCNOQCPPDAPNRDQLCDSNPBPPJDPITAMPBBPRLBMQIDTMNBRSICQTLBULFBSKPDROCBRIMDPUHBPHQDPSJDMSNDPLDBMMOALLHDRHKBKPGBNIKAJLFAVLSDQUACWMOBTMEAVOMDSREA",
            "MMUAKMPDKKCDKOKDKQIDMKPAKRGAJNOCNNADHMQDIPJCGQNDKMHAKHKAGMECMHQAJIABOLMDKTEAKWRDMSBCJWSCGOBDILNDPNDDOGLCFOFCNITAKQGALFMARLJBKYRDMYIANROANQDDSMLDGWFDHRTAQRHB",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAOJNBMPGAQNQAINCAIQRDMJABNQOAJJDDJRQASOEBJTRAPPCBPRSAKPIBHILAUPICRMMDLPADUNTDRPFBURLCKIHDPUKDJMJCJQKDVRGDMHPCWPHC",
            "MMUAKMKAMKIAIMNDJKICJNQBNMEDIIQBGJDCFILCEJDBKNOCIGABIMMAHLGCKIOADKFBHONDJGHAEMMBEICALGKAMHAAEGPBCHCACLPBBMHBNOLCBPJDFLSCKFBCCNRAKFEBOIRDMOGDEETBBEFAEOSBEKBB",
            "MMUANMLDNNGAMOTBNQFBKMLDLLJDOLRDOLDBJMPCORADQNSBRLICJKQDPOHBHJKAKQEAGISDJRJCPNOAKPFCNSKBITACHPNDFIECROOAQQBBOSTAGQBAOJMCKTDDGMRDFICDPIPDSJICFLMCTHGAFQQCUIHA",
            "MMUAMKNAMPCCONMBNJDCNQSBLQFBPOPAOREANJRBQNDDPKNCOTBBORKBKKGAKMSAKRCBPTPDQUGBOOKDKPICMTTCQRIAOLRBSUJCLUMBKIAAROQARLJCRJLDIJBDOPQBKWHCHRTDTUHDMHOCGPABJNLBJYFD",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAMPSAMLDANKKCQPJCMSQCMJHCRLRCNSEDKPMBTLACNITDKRABTJPCQRCCSILCLHBAKUQDJIGDMFNAPHIBUJPDUHFCSIKBOFHDOKRDXJCBWILCQJGA",
            "MMUAKNQDLLCBJNNCLMJDHMTDNLJCONQCJKHBFLLDEJGAJJMDPLGAMOTALKHDDJOBGIBCAJRAJPBCKHSBDJCAMRNCRKABNOPCHKECLQSCMKFAGLPCNRFALQKBPKDCGPOASMIBJNMAOOAAGRRBKSEDOOLDSPIC",
            "MMUAKNMAIOIDMOKAMLFDJQKDIPBBOMMBPMDAMNLBLJHALPRBMQJAQOPCMLDAHMOAPQECSMOCORGAGMTCTNHCPONDPLCDNJTAKLJCGNPBVMEBPQSBVPGCLMLCRPFDQQQAGQAAQLNBTOABFSSCMIICKMQDLGBD",
            "MMUANLQAPLEAMKTDMOCAPJSBLQCDLLMDKOJBHOMDOPHBRKOBORBBHPKBMSFCPHNANIADQILAPNBBQGPDSHHAJKTAREJCJNODSFIBTEPASKGDNFRALUACHORATDICUHLATLEBNEQDQPDDPKNDIQDDRRKDRCFD",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAMKSDNJDDROQCMQGDMIKCNHBDJPPAJRIALGLBMOICPQLDPREAQHTCIPACOFOAOTFCRMRCPJJAMUQAGPHBEPMCGPHAMPKBSNGAKVPAPTAALSRDSQCC",
            "MMUANMMDOLFDLMRBLKDAQLTDPJHANNSARMIASJMCOPBBMQKCJMIBQMQBUMCCVNNBKLHCQPPDIOJDGONDIPGBUNODTHBCWLKBJPJAPQSDKJGDLOTBVQADUPPBQIFCFOLBQIDBTRLAOKEAFQOAKKADSNRACOEA",
            "MMUAMOOBMOACKMTDNNGDOOMBORJCNKNAJNHDOSPBOIHBKOSBJQFANSLDKMCCJSKAMSABPMSBMQIAHOPAQLIBHTRAKUGDLVMBPHDCFOKAPTEAHMTAOUBBMJNAIRECPRQDSRCCPKRDOJJBKWOBNHBCMWLARPFA",
            "MMUAKMRDKOICIMKDNOACOPTDPRJDMPKBPSFALLPDHOGDJQNCOQABMNQDSRDCKKLCKHFBQOMCTSHBHKOALJHDKGLDNICATUQAQUEBPVNBPSBDOOOAPXEBUVMASTCBUXPAGODBMHSBVZBDOHSCSRIBGKRBNFJB",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAONLBNJFBIMNDPQICHMQBQOJDRNPDJNABIPPAJKEDGNQBKQGDHKLBQRHDNRRCTMCCLRKBJHHAMTSCRPAATRMCLGGAURTDUNIBOIKAFMDCLVRDVTBC",
            "MMUAMPOCNPDAPOKARNGBQMMDLRIDSPTDJPADKSRDTNFANNLANRHALRRAQMHAIRTAHRDBUONARLEDQPQAIQIDHQQCSRJCJNMDRJFDHNSBSTBCSVPCMKCASWOBILJBNMKDURACWRSCYRCBHULDUXECWNNCSIBD",
            "MMUANNMAOPEDPONDMLJCNMKDOLBDNQSCKQFAMOTBKSAAQPQAQSBCSRPCKMAAQURCTRHDUSSBPKIDITLDRVDDQINAPVJARWOBOXCDQGMAJOICRYOBIVGCTRPCSSEBSKRBNSGBMNTALUCCMWKAWRDBQMLAVQFC",
            "MMUALLKBOMICQMLCOOGDROSCSPECNOOBRLADRINBSKCDVKKCLOGBRRODSNBDQRQBUOJBMQTCPHHAPKQCUMIAQUMDOSDAMRTARVFBPGPDTVECNUSCJNJAPDRBNLCCQRMAIODBJLNCPVABRYPCRTBDVORDPCFC",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAQNPDILBASMLBQOIASKKBINABQKLCJPCDPIQATOIBQHKDQNCBPKRDROADPGNBMPHAHOMBJKJCKJSDLRHCIQTBKTDDLPQBSJGCEORDSHEDOEPAUIFB",
            "MMUALLPBKNDCJLRCIOGAKJKAKOJALITCMKBDJJNCKRACNHRCKMDALRODJGHBJKKAPHHBNMTDINGCJTSCKSJAGJMDQGECRHLCFHFDPLNARJEDQGQDGOBANQQAFIIBTGSCKVICUGPDEPCANNOALFABRKLBKECD",
            "MMUALORAMLIDOLNALRADNPLCPNJBKSODKUFDPPRAORJDNQTBMRADNPKBOSGAKLNDPJBAJLPBSPHBHKSAPIECMTTDNKFDQTQDJVCCITMAQRHDIWSASOIDLVOBLNCCUPMCHYDDQKQATKECKPPBLRGCSILAHPDD",
            "MMUAOMTBNKDALLNAMJIBKKQCMPACLNPBMHFBNOPDKHCBNLMBOJDDQKKDNPIAJJRCQIBCNNNAPIEBJGLDPOHARIMAPNGDHKODIMJCFMSDKQECTIKAKRBASLSDVLJBJHLDGNCBNSRDIPFBJDOBGKHCLGTDOOGA",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFARMKCQNCAQNQBKQCDPMKDQKHBLJOALQICPIRBOHGDQMRBKRJANRLCJSECLHSBJGIDPPQAJRFAJTPBLFBCJPMCJJGAINTBMDHCQGLCHGDDRLPBMPAA",
            "MMUAKNPAKMADLOSALQJBLKOAMSHDKOMDMPGALTQDKRFBJOLBKTIBMSLAOMICIUTCJNBCKKTCFUJAOQRBNTEAJJKCEVABIKQBFVECLJNDJVDAPQRDJOBCKXSBMMGBEUMCIYFDOUOAGVCAQMPBKOCCHXNCLGDB",
            "MMUALMSCKODDONNBOPGBIMRDLJJBHKKAHICBKPLBNJFCOIODHPFAGMOANGGDOGMBNEEDIKMBMCIAPMQCMOEARMPBPPHDIQTALQCAMETBQQHBINLAKKABSLPCKNJBNNSAKLBDPMKDGQACRSQCPHDDMGNBTLID",
            "MMUAMORANMGDNQLCOOIDKNTDOKAAJOOCPMBDMKNDKLDCLLNDKODANRTAMLCBOLKCOPCAINRCQOJDOQOCLJJCNJSDRQECTQMBLRECTTQDKTBCUUPBMTHDNJSBNVGDISKBKRFAVQMCSOADHLQDRUHDWULCNXFC",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAQMPDROFCJKKAHLJAKKNBLKHDFLQDSMDDUNPDRPGBWNLAUMBBNKTDJOEASOSDMOACFMKAGNIAHORAYNHAJJRCGMABRROBEKGBJQMBLOCDPRLCOTID",
            "MMUAMPTDOOGCOQKCMKEANLQAPREDQLPBNSFCRLPAQKADKLOATLGDQLKCNUHDTNSDPKHCPMRBMUICQSSBRSJDLKMCUSDBUQLAVOBAUJRAWLFBPONAUIIDWSNCKOCDSQODRNABJLQBSTCAKKMAXRJDOILBLWBC",
            "MMUAMPMDLPDCMQPBLMICLKQCORJCPQTAQRIAMTNDKIABLJKBMLHDMRLAJPCBJORDNNGALUSDJMJCMQTCKRFCJPSAMTBARTQDPSEBKTMCIOACPMRAPLECUTNCNVBDGPPAIRFCTUOASSHDUROCUODAEPKAQSCD",
            "MMUAMPNCJPEDKRTCKOBDNOPDOMICNQSDNSDCHRNALLGDNNLBISCAPRLBIRBAKJPBPQADGSOCPNEAIKRAHTJBPMKDIJGCRRQBSNFCGKKCMQJBKTTCROAANPMBHVHBPOMCUOHCIGOBJWFBESRBHYDDUPSAEJCB",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAOONDQLAAJPODHPIAMJQAHOFDGMKAPQECOKSDFQHAGSLDMHDBIRMBQLIBGOLBLQGBEOPCHNCCJTRDNIGDMHRAGKAAGRPBFMBCHTKBJMCBMPQAKRJB",
            "MMUAMKNBMPCCKNPDJODCOLLBHOECOKPDLRACRKMCPIEAIQODPJDCGPOAOPJBSISANRBDGNLCHNFBSLNCKJHDTMSCFLFANQKAQRJCUKTCILHBDMQDGKBCOORDVIGBTOTDOOAAJLQAJICCQORDKTIDPTKDPPIA",
            "MMUANORCONDARNTCNOADTMLCNMFDLLODNKFCQLSAQJGANPQBMQBBPIRAMQHAORQDQRJDLSNAUMDDLVOCONGDJKKDSSABIKNCJHHAQHSCLMIBJUPBRSCDWNKBJFIBJWTAQOBASJMAXOEALWMAOTEDIXPBIVCB",
            "MMUALONDMQJCLRTBLMCCKLLCNPIDKSNBJKDCKROAIRHBPPMDGQHBRQKDQQFBEPTDNQFAPRQBSRCALNRDTTBDQQMDDOABPUQDOUJBMSSAKIGBNRPADRGDDPLDOXBDUSODMPDANNSDWREBKOKCGSEBNKPAUSIC",
            "MMUANLOBLNBCONSCKLDAPOTCMLEBPLMBKNJDOLNBLOFAMPPANJCBQPODJLHCSPPDRQEBSMRALKADNNTDSRGAMJMAPPIBGLQATTACJNKBTLFCELLAVRGCJPRACMBAMLSANQJAAMQDJIDAUPKDIJICVMNBRLHC",
            "MMUANMNAKMDAJOOCMLHCIMRDGMFDKOKAJLCDQMLCNOBBFKTAHOECJIKBIPJAFOPCMIEADKSAJHDCFQTCNRGCESNDPNAASLRBKJHAHKQDDRACMGMBSNJBKILDMPGBEUMDOPCANGSDGHIAJOPABLBDBIOABSIC",
            "MMUANNLANMBDPLLCKNEAKPOANQHDLMMCIPCALQKAJRABKQTDQKCDQNKBIRJDRLPAJUDCROTDONIDSQOCMNHDIMRDHRDCTLSAIVGBTRNBMSJDQMSCOSGDRRQBOOIAGPPAKWFCHSMBKYFCUMNANOBAHKRAPTAB",
            "MMUANNODMLFCPOLBLKHCPQMBPTEDJJTAQVGCMPLDILEAPMRCRSABOSNCKPCDPQSCRWGBMNPAQMADSSKAJQBCRPQCSXHAHRTAJHFBGMNAPSDDPXQCJNIAIPSCPKIDFNOBFLBAOVRCTQCAEMKCPYJANTMBFPDB",
    };

    static final int SCORES[] = {
            22, 26, 4, 10, 12, 24, 16, 8, 24, 22, 6, 5, 4, 12, 12, 6, 8, 30, 18, 8, 6, 20, 10, 7, 22, 18, 7, 11, 5, 10, 6, 6, 6, 22, 6, 4, 18, 7, 10, 7, 16, 18, 16, 10, 8, 5, 20, 10, 39, 20, 9, 12, 7, 12, 16, 12, 28, 21, 5, 7, 10, 6, 5, 5, 24, 20, 11, 7, 8, 7, 12, 10, 45, 30, 8, 3, 16, 6, 12, 16
    };

    static final String INVALID_PLACEMENTS[] = {
            "MMUAOONB",
            "MMUANNNB",
            "MMUANONCMNED",
            "MMUANONCLLEAMNMD",
            "MMUANONCLLEAOMMD",
            "MMUANONCLLEANOMC",
            "MMUANNODMLFCPOLBLKHCPQMBPTEDJJTAQVGCMPLDILEAPMRCRSABOSNCKPCDPQSCRWGBMNPAQMADSSKAJQBCRPQCSXHAHRTAJHFBGMNAPSDDPXQCJNIAIPSCPKIDFNOBFLBAOVRCTQCAEMKCPYJANTMBQZDA"
    };

    static String badlyFormedTilePlacement(Random r) {
        char a = (char) ('A' + r.nextInt(ROWS));
        char bada = (char) ('A' + ROWS + r.nextInt(r.nextInt(BAD)));
        char b = (char) ('A' + r.nextInt(COLS));
        char badb = (char) ('A' + COLS + r.nextInt(BAD));
        char c = (char) ('A' + r.nextInt(TILES));
        char badc = (char) ('A' + TILES + r.nextInt(BAD));
        char d = (char) ('A' +  ORIENTATIONS);
        char badd = (char) ('A' + ORIENTATIONS + r.nextInt(BAD));
        String test = "";
        switch (r.nextInt(5)) {
            case 0:
                test += "" + bada + b + c + d;
                break;
            case 1:
                test += "" + a + badb + c + d;
                break;
            case 2:
                test += "" + a + b + badc + d;
                break;
            case 3:
                test += "" + a + b + c + badd;
                break;
            default:
                test += "" + bada + b + badc + badd;
        }
        return test;

    }
}
